image: java:8

before_script:
    - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew clean build -PdbHost=postgres
  allow_failure: false

test:
  stage: test
  script:
    - ./gradlew -g /cache./gradle check -PdbHost=postgres

services:
  - postgres:latest

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password